### ISSUE TITLE
Issue in Saving output Files

### ISSUE THREAD

**Issue by tejshahi** [Poissonfish/GRID#1]
**Describe the bug**
ValueError: could not convert string to float: 'C12'
**To Reproduce**
St
![Error in writing](https://user-images.githubusercontent.com/1841958/85824252-b5cef880-b7c2-11ea-958e-d4377098b9a2.png)
![Error in writing](https://user-images.githubusercontent.com/1841958/85824302-d39c5d80-b7c2-11ea-9e31-6583fe94a96d.png)

eps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Poissonfish** [comment]
Hi,

Sorry for the late reply. This issue should have been resolved in the latest version of GRID. Please update your GRID and see if the issue still exists. Thank you for your feedback!

James
