### ISSUE TITLE
Band order

### ISSUE THREAD

**Issue by brookjason** [Poissonfish/GRID#10]
I was having a play with your gui software and I added one of my mulispec images. The images have 6 bands in the following order:

1. Blue (RGB camera): Center 470 nm, Width 120 nm
2. Green (RGB camera): Center 550 nm, Width 100 nm
3. Red (RGB camera): Center 620 nm, Width 110 nm
4. Red: Center 650 nm, Width 40 nm
5. Red Edge: Center 710 nm, Width 20 nm
6. Near IR: Center 850 nm, Width 100 nm
 
This will effect the caluclation of NDVI etc, is there a way to specify the bands? or could there be a place to specify bands?

**Comment by Poissonfish** [comment]
Hello,

You might want to follow the tutorial here: https://poissonfish.github.io/GRID/ch4_adv/custom_index.html
GRID will export the information of each band in the right order, so you can come up with your desired index.

**Comment by brookjason** [comment]
Thanks for the responce, i thought i may have to re calculate the indecies from the individual bands
