### ISSUE TITLE
Software crash

### ISSUE THREAD

**Issue by chabrault** [Poissonfish/GRID#15]
Hello,

Thank you very much for this nice application!

In the 3rd step (60%), when I define the plot centers, the software crashes if I left-click and right-click to add or remove plot centroid.
Also, at the last step, if I click on the "Browse" button, the software crashes.

I run the GRID 1.3.9 on a Window computer, with Python 3.11.

Charlotte

**Comment by Poissonfish** [comment]
Hi Charlotte,

Would you share the error messages you saw in your Terminal? 

James

**Comment by chabrault** [comment]
Sorry I forgot to include that.
For the first crash (for plot centroid), the terminal prints:
`
File "C:\Users\cbrault\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\grid\gui\anchor.py", line 450, in mouseReleaseEvent
    objMap.delAnchor(self.idx_tool, self.idxAnc)
  File "C:\Users\cbrault\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\grid\gmap.py", line 277, in delAnchor
    self.sigs = np.array([sigMaj, sigMin])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.
PS C:\Users\cbrault\Desktop>
`
For the last crash when I click on "Browse", the terminal prints:
`Traceback (most recent call last):
  File "C:\Users\cbrault\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\grid\gui\outputer.py", line 303, in assign_PathOut
    self, "", "", QFileDialog.ShowDirsOnly
                  ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'QFileDialog' has no attribute 'ShowDirsOnly'
`
I hope it helps,

Charlotte

**Comment by Poissonfish** [comment]
Hello Charlotte,

Thank you very much for your feedback. The issues have been resolved. Please open GRID again and see if you are prompted to upgrade the version to 1.3.11. If you still encounter any problems, please let me know. I appreciate your help in making GRID a better software!

Cheers,
James

**Comment by chabrault** [comment]
Hello James,

It works, thank you!

Charlotte
