### ISSUE TITLE
Couldn't load SIP module. Python support will be disabled.

### ISSUE THREAD

**Issue by abdulhafidz6** [Poissonfish/GRID#2]
Hi..
After installing all of the dependencies through QGIS OSGeo4W shell, I could run GRID script in the QGIS command prompt. Unfortunately, All of my python plugins include pythons it self in QGIS were disabled. I followed the suggestion from this link https://github.com/qgis/QGIS/issues/37783#issuecomment-668553559, include removing pyqt5 module and it still disabled.

Couldn't load SIP module.
Python support will be disabled.

Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\PyQt\QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ModuleNotFoundError: No module named 'PyQt5.QtCore'

Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.16.1-Hannover 'Hannover', b381a90dca

Python path:
['C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python', 'C:/Users/hp/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/hp/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\Scripts', 'C:\\Program Files\\QGIS 3.16\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.16\\bin', 'C:\\Users\\hp\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\Pythonwin']

**Comment by abdulhafidz6** [comment]
Hi again,,
I reinstall into QGIS3.16.2 and reinstall Photo-Grid through QGIS OSGeo4W shell but still happen

Couldn't load SIP module.
Python support will be disabled.


Traceback (most recent call last):
  File "", line 1, in 
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\__init__.py", line 70, in 
    from qgis.PyQt import QtCore
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\PyQt\QtCore.py", line 24, in 
    from PyQt5.QtCore import *
ImportError: DLL load failed: The specified procedure could not be found.


Python version:
3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]

QGIS version:
3.16.2-Hannover 'Hannover', f1660f9da5

Python path:
['C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python', 'C:/Users/hp/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/hp/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python/plugins', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\Scripts', 'C:\\Program Files\\QGIS 3.16\\bin\\python37.zip', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\DLLs', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib', 'C:\\Program Files\\QGIS 3.16\\bin', 'C:\\Users\\hp\\AppData\\Roaming\\Python\\Python37\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS3~1.16\\apps\\Python37\\lib\\site-packages\\Pythonwin']

**Comment by Poissonfish** [comment]
My apologies for my late reply and any of your inconvenience. Somehow GitHub stops sending me emails for new issues. Would you show me the GRID version you downloaded and the screenshot? 

Currently, GRID doesn't support running in QGIS terminal. You have to run it on Python directly (in terminal or command prompt). Please see the [link](https://poissonfish.github.io/GRID/ch1_started/installation.html) to get started.
