### ISSUE TITLE
Problem when I run grid

### ISSUE THREAD

**Issue by frchalaoux** [Poissonfish/GRID#3]
**Describe the bug**
When I run grid with I got an error

**To Reproduce**
1. Go to to your environment where is installed grid
2. Run on 'python -m grid'

(IA) frchalaoux$ python -m grid
Traceback (most recent call last):
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/site-packages/grid/grid.py", line 8, in <module>
    from .guser import *
ImportError: attempted relative import with no known parent package
(IA) frchalaoux$ python -m grid
Traceback (most recent call last):
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/site-packages/grid/grid.py", line 8, in <module>
    from .guser import *

**Expected behavior**
Start the application

**Desktop (please complete the following information):**
 - OS: MacOS Mojave
 - Anaconda 3
 - Python 3.7.6

**Comment by Poissonfish** [comment]
Hi, 
Thanks for the report. I need some extra information to confirm the issue:
* Would you print out the output of `ls -alht /Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/site-packages/grid/`
* What's the GRID version? You can print the info by the command `pip show photo_grid`

**Comment by frchalaoux** [comment]
Hi, 

here is the information. Any idea ?

**(IA) frchalaoux$ ls -alht** /Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/site-packages/grid/
total 360
drwxr-xr-x    4 frchalaoux  staff   128B 24 mar 08:39 demo
-rw-r--r--@   1 frchalaoux  staff   6,0K 23 mar 17:12 .DS_Store
drwxr-xr-x   20 frchalaoux  staff   640B 23 mar 17:10 .
drwxr-xr-x  460 frchalaoux  staff    14K 23 mar 17:10 ..
drwxr-xr-x   15 frchalaoux  staff   480B 12 déc 19:31 __pycache__
drwxr-xr-x   10 frchalaoux  staff   320B 12 déc 19:31 gui
drwxr-xr-x    3 frchalaoux  staff    96B 12 déc 19:31 res
-rw-r--r--    1 frchalaoux  staff    20K 12 déc 19:31 lib.py
-rw-r--r--    1 frchalaoux  staff    16K 12 déc 19:31 io.py
-rw-r--r--    1 frchalaoux  staff   1,1K 12 déc 19:31 guser.py
-rw-r--r--    1 frchalaoux  staff    25K 12 déc 19:31 gtest.py
-rw-r--r--    1 frchalaoux  staff    12K 12 déc 19:31 gridGUI.py
-rw-r--r--@   1 frchalaoux  staff   8,7K 12 déc 19:31 grid.py
-rw-r--r--    1 frchalaoux  staff    11K 12 déc 19:31 gmap.py
-rw-r--r--    1 frchalaoux  staff    10K 12 déc 19:31 gimage.py
-rw-r--r--    1 frchalaoux  staff    28K 12 déc 19:31 gagent.py
-rw-r--r--    1 frchalaoux  staff    94B 12 déc 19:31 dir.py
-rw-r--r--    1 frchalaoux  staff   4,1K 12 déc 19:31 benchmark.py
-rw-r--r--    1 frchalaoux  staff   518B 12 déc 19:31 __main__.py
-rw-r--r--    1 frchalaoux  staff   4,6K 12 déc 19:31 __init__.py


**(IA) frchalaoux$ pip show photo_grid**
Name: photo-grid
Version: 1.2.13
Summary: A GUI for field segmentation
Home-page: https://github.com/Poissonfish/GRID
Author: James Chen
Author-email: chun-peng.chen@wsu.edu
License: GPLv3
Location: /Users/frchalaoux/opt/anaconda3/envs/IA/lib/python3.7/site-packages
Requires: pyshp, opencv-python, scipy, numpy, image, h5py, tqdm, qdarkstyle, rasterio, PyQt5, pandas, matplotlib, sklearn
Required-by:

**Comment by Poissonfish** [comment]
Hi,

Sorry for my limited knowledge of Python, I can't replicate this issue. It could have something to do with where you run GRID, you want to run GRID outside of the package folder. Or maybe you can try running it outside of Anaconda?

**Comment by frchalaoux** [comment]
Hi James,

Thanks a lot for your help.
I will try to launch GRID outside these locations and tell you.

Cheers,

FRC
