### ISSUE TITLE
I missed the bug when I run commend "python -m grid"

### ISSUE THREAD

**Issue by YixiangShan** [Poissonfish/GRID#4]
**Describe the bug**
Hi, I created a new environment in anaconda and installed the "rasterio" and "photo_grid", following the instructions. Then I run the commend "python -m grid". But it failed to open the demo.　

**To Reproduce**
1. create a new environment named "GATTING" and activate it: 

> `conda create -n GATTING`
> `conda activate GATTING`

2. install the rasterio

> `conda config --add channels conda-forge`
> `conda install rasterio`

3. install the photo_grid

> `python -m pip install photo_grid`

4. launch GRID

> `python -m grid``

5. The result is:

> ~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
>                  Welcome to GRID Ver.1.2.15
> ~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
> Author      : James Chen <chun-peng.chen@wsu.edu>
> Last update : Feb 23, 2021
> User manual : https://poissonfish.github.io/GRID/
> ~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
> Recent update
>     - Add CRS to shapefiles (.prj)
>     - Update user manual
>     - Support ESRI shapefile compatible in QGIS
> ~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~*~~~~~~~~~
> Traceback (most recent call last):
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\runpy.py", line 188, in _run_module_as_main
>     mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\runpy.py", line 147, in _get_module_details
>     return _get_module_details(pkg_main_name, error)
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\runpy.py", line 111, in _get_module_details
>     __import__(pkg_name)
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\site-packages\grid\__init__.py", line 72, in <module>
>     from .grid import *
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\site-packages\grid\grid.py", line 9, in <module>
>     from .gimage import *
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\site-packages\grid\gimage.py", line 6, in <module>
>     from .io import *
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\site-packages\grid\io.py", line 12, in <module>
>     import rasterio
>   File "D:\Coding\Anaconda\Anaconda\envs\GATTING\lib\site-packages\rasterio\__init__.py", line 9, in <module>
>     from rasterio._base import gdal_version
> ImportError: DLL load failed while importing _base: 找不到指定的程序。

**Expected behavior**
The program runs normally.

**Screenshots**
![bug in GATTING](https://user-images.githubusercontent.com/63697648/119235559-fea24500-bb2a-11eb-8019-a166c02d6cee.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]　Windows 10
 - Browser [e.g. chrome, safari]  chrome
 - Version [e.g. 22]　Python 3.9.4

**Additional context**
I am a python beginner but I am really interested in this phenotyping program. I have tried the methods online, which asked me to install the packages again. Finally, I failed. Hope to get the answer. Thank you very much.

**Comment by Poissonfish** [comment]
Hi,
Thanks for the feedback. This issue should be related to loading rasterio under Conda environment. I can't replicate your issue without looking into your environments settings (such as `condo info`), but I found some threads that might be helpful:

https://github.com/conda-forge/rasterio-feedstock/issues/149
https://github.com/ioos/conda-recipes/issues/775
https://stackoverflow.com/questions/55596662/rasterio-and-gdal-dll-load-fail-in-pycharm

Please keep me updated how does your case go, thank you.

James

**Comment by YixiangShan** [comment]
Thank you, James. The `conda info` is shown as the picture.

> 
![conda_info](https://user-images.githubusercontent.com/63697648/119334139-a8481a00-bc82-11eb-8312-da9a6ccfa028.png)

I try this method (https://stackoverflow.com/questions/55596662/rasterio-and-gdal-dll-load-fail-in-pycharm). But I can not install gdal.

![install gdal](https://user-images.githubusercontent.com/63697648/119335060-bf3b3c00-bc83-11eb-91a8-b7cf929f0377.png)
![conda list](https://user-images.githubusercontent.com/63697648/119335064-c2362c80-bc83-11eb-83da-575cce522e07.png)

Is the gdal influnce rasterio running?

Thank you,
Yixiang

**Comment by Poissonfish** [comment]
Seems you need to install gdal that support Python 3.9. According to your log, gdal-2 only support Python < 3.9
