### ISSUE TITLE
libQt5Core.so.5: version `Qt_5.15' not found

### ISSUE THREAD

**Issue by tectal** [Poissonfish/GRID#8]
**Describe the bug**
After running python -m grid, "ImportError: /lustre/yangyong/anaconda3/lib/libQt5Core.so.5: version `Qt_5.15' not found (required by /lustre/yangyong/anaconda3/envs/grid_3.8.1/ lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so)"

**Expected behavior**
I follow the tutorial

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
python: 3.8.1
![32f0614f486cabd153fd415059cd11c](https://user-images.githubusercontent.com/10612361/144710766-c9e62509-20eb-42f7-8c53-e8fb89fbb82c.png)

**Comment by Poissonfish** [comment]
Seems your environment didn't link to the right QT library. (Should be under "./anaconda3/envs/grid_3.8.1/lib/"). You can try to fix this by the solution I found below:
> Issue happens because you have Qt installed in /usr/lib/x86_64-linux-gnu from distro which ld will use by default. To avoid such issues you can compile with -rpath or run with LD_LIBRARY_PATH=/path/to/your/Qt/libs/location to help linker find needed Qt version.

[reference](https://stackoverflow.com/questions/36128645/error-on-execution-version-qt-5-not-found-required-by)
