### ISSUE TITLE
from rasterio._base import gdal_version ImportError: DLL load failed: 找不到指定的程序。

### ISSUE THREAD

**Issue by tectal** [Poissonfish/GRID#9]
**Describe the bug**
from rasterio._base import gdal_version ImportError: DLL load failed: 找不到指定的程序。

**To Reproduce**
I installed it in win according to the tutorial, and after python -m grid, it appeared: from rasterio._base import gdal_version ImportError: DLL load failed: The specified program could not be found.
![image](https://user-images.githubusercontent.com/10612361/144816705-e99886ba-d4c1-4aa2-bcbf-fae88fbecf77.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version python=3.7.3

**Comment by tectal** [comment]
I tried https://stackoverflow.com/questions/55596662/rasterio-and-gdal-dll-load-fail-in-pycharm, but it didn't work

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/144817047-c0ebc6a8-334e-4bb7-95b2-7d852a44f4ea.png)
![image](https://user-images.githubusercontent.com/10612361/144817109-09d152e7-97af-4332-8a4a-04f5953423bf.png)
![image](https://user-images.githubusercontent.com/10612361/144817134-722240ec-fe92-439e-8be2-ec531abe3f8c.png)

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/144817322-7d462df6-620b-4128-a437-44f5c13bf758.png)

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/144817555-69c12b2e-127b-4c3b-9b39-fb5ccd7ef01e.png)

**Comment by tectal** [comment]
![image](https://user-images.githubusercontent.com/10612361/144817723-1b5066ad-c462-4a90-9ec0-2e700eed7fe5.png)
Can import rasterio normally

**Comment by Poissonfish** [comment]
Thanks for the update. Next time please put the logs into code blocks for better readability.

It's hard to me to see the problems given the provided screenshots. Would you show me how you installed rasterio? And would you try 
* Installing an older version of it (e.g., 1.0.21)? or
* Installing it through binaries or source distributions.

Windows usually requires more effort in configuring the PATH variable compared to UNIX systems.
